name: Deploy to Vercel

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_SPOTIFY_APP_CLIENT_ID: ${{ secrets.VITE_SPOTIFY_APP_CLIENT_ID }}
          VITE_SPOTIFY_APP_CLIENT_SECRET: ${{ secrets.VITE_SPOTIFY_APP_CLIENT_SECRET }}
          VITE_SPOTIFY_BASE_URL: ${{ secrets.VITE_SPOTIFY_BASE_URL }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        run: |
          npm run build

      - name: Deploy
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.SVELTE_SPOTIFY_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.SVELTE_SPOTIFY_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.SVELTE_SPOTIFY_VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
